# Generated by Django 2.2.6 on 2019-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, default='', max_length=250)),
                ('physical_description', models.TextField(blank=True, default='')),
                ('behavior_description', models.TextField(blank=True, default='')),
                ('habitat_description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
