# Generated by Django 2.2.6 on 2019-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(null=True, upload_to='animals'),
        ),
    ]
