# Generated by Django 2.2.6 on 2019-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20191103_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='animal',
            name='mental_characteristics',
            field=models.ManyToManyField(to='animals.MentalCharacteristic'),
        ),
        migrations.AddField(
            model_name='animal',
            name='physical_characteristics',
            field=models.ManyToManyField(to='animals.PhysicalCharacteristic'),
        ),
    ]
