# Generated by Django 2.2.6 on 2019-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('animals', '0004_auto_20191108_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentalCharacteristic',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='mental_characteristics',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='physical_characteristics',
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(to='animals.Tag'),
        ),
        migrations.DeleteModel(
            name='PhysicalCharacteristic',
        ),
    ]
