# Generated by Django 2.2.6 on 2020-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20191108_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
